NUMERICAL_FEATURES = ["AGE", "ANNUALSALARY"]
CATEGORICAL_FEATURES = ["GENDER"]
FINAL_FEATURES = ["AGE", "ANNUALSALARY", "GENDER_FEMALE", "GENDER_MALE"]

CATEGORIES = {
    "GENDER": ["MALE", "FEMALE"]
}

DEPENDENT_VARIABLE = "PURCHASED"
